import AurthWrapper from "@/components/containers/AurthWrapper";
import PageWrapepr from "@/components/containers/PageWrapepr";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <main>{children}</main>;
}

//  TODO: make seperate container for checkboxes
